/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.conexao;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.tableModel;
import javax.swing.ListSelectionModel;
import model.Funcionario;

/**
 *
 * @author Pichau
 */
public class ConFunFrame extends javax.swing.JInternalFrame {
    
    conexao con_bd;
    String sele;
    String campo;
    tableModel modelo;
    
    
    private Funcionario func;
 
    public ConFunFrame() {
        initComponents();
        
        con_bd = new conexao();
        con_bd.conecta();
        con_bd.executaSQL("select * from tab_funcionarios");
        
        
        preencherTabela("select * from tab_funcionarios order by nome_func");
        
        
        BtnBuscar.setMnemonic(0);
        
        BtnBuscar.setEnabled(false);
        TxtCampo.setEnabled(false);
    }
    
    public void preencherTabela(String sql){
        ArrayList dados = new ArrayList();
        
        String[] colunas = new String[]{
            "Nome",
            "CPF",
            "Cidade"
        };
        
        
        con_bd.executaSQL(sql);
        
         try {
             con_bd.resultset.first();
             do{
                 dados.add(new Object[]{con_bd.resultset.getString("nome_func"), con_bd.resultset.getString("cpf_func"), con_bd.resultset.getString("cida_func")});
             }while(con_bd.resultset.next());
         } catch (SQLException ex) {
              JOptionPane.showMessageDialog (null, campo + " não existe no campo " + CboCampo.getSelectedItem(),"Preencher Tabela", 2);
              TxtCampo.setText("");
              BtnBuscar.setMnemonic(0);
              BtnBuscar.setEnabled(false);
              TxtCampo.setEnabled(false);
              preencherTabela("select * from tab_funcionarios order by nome_func");
         }
         
         modelo = new tableModel(dados, colunas);
         
         TblClie.setModel(modelo);
         

         TblClie.getColumnModel().getColumn(0).setPreferredWidth(250);
         TblClie.getColumnModel().getColumn(0).setResizable(true);
         
         TblClie.getColumnModel().getColumn(1).setPreferredWidth(110);
         TblClie.getColumnModel().getColumn(1).setResizable(true);

          TblClie.getColumnModel().getColumn(2).setPreferredWidth(136);
         TblClie.getColumnModel().getColumn(2).setResizable(true);

         
         TblClie.getTableHeader().setReorderingAllowed(false);
         TblClie.setAutoResizeMode(TblClie.AUTO_RESIZE_OFF);
         TblClie.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         
        
        
    }
    
    public void setPosicao() {
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CboCampo = new javax.swing.JComboBox<>();
        LblCampo = new javax.swing.JLabel();
        TxtCampo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblClie = new javax.swing.JTable();
        BtnBuscar = new javax.swing.JButton();
        BtnReca = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.inactiveCaption);
        setClosable(true);
        setTitle("Funcionários");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel1.setText("Campo a pesquisar");

        CboCampo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CboCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Endereço", "Data de Nascimento", "Data Admissão", "CPF", "Cidade", "Cargo", "Email", "CEP" }));
        CboCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboCampoActionPerformed(evt);
            }
        });

        LblCampo.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        LblCampo.setText("Campo:");

        TxtCampo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TxtCampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtCampo.setEnabled(false);

        TblClie.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        TblClie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TblClie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblClieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblClie);

        BtnBuscar.setBackground(new java.awt.Color(153, 255, 153));
        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/consulta.png"))); // NOI18N
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnReca.setBackground(new java.awt.Color(153, 153, 255));
        BtnReca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/limpar.png"))); // NOI18N
        BtnReca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CboCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblCampo)
                                .addGap(18, 18, 18)
                                .addComponent(TxtCampo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnReca, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(CboCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LblCampo)
                                .addComponent(TxtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BtnReca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboCampoActionPerformed
        sele = (String) CboCampo.getSelectedItem();
        BtnBuscar.setMnemonic(KeyEvent.VK_ENTER);
        BtnBuscar.setEnabled(true);
        TxtCampo.setEnabled(true);
        if (sele.equals("Nome")){
            sele = "nome_func";
        } else if (sele.equals("CPF")){
            sele = "cpf_func";
        } else if (sele.equals("Endereço")){
            sele = "ende_func";
        } else if (sele.equals("Data de Nascimento")){
            sele = "data_nasc_func";
        } else if (sele.equals("Cidade")){
            sele = "cida_func";
        } else if (sele.equals("Cargo")){
            sele = "cargo_func";
        } else if (sele.equals("Data Admissão")){
            sele = "data_admi_func";
        } else if (sele.equals("Email")){
            sele = "emai_func";
        } else if (sele.equals("CEP")){
            sele = "cep_func";
        } 
    }//GEN-LAST:event_CboCampoActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        campo = (String) TxtCampo.getText();
        preencherTabela("select * from tab_funcionarios where " + sele + " like '%" + campo + "%'");
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnRecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecaActionPerformed
        preencherTabela("select * from tab_funcionarios order by nome_func");
        TxtCampo.setText("");
        BtnBuscar.setMnemonic(0);
        BtnBuscar.setEnabled(false);
        TxtCampo.setEnabled(false);
    }//GEN-LAST:event_BtnRecaActionPerformed

    private void TblClieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblClieMouseClicked
        int linha = TblClie.getSelectedRow();
        Object cpf = modelo.getValueAt(linha, 1);
        
        
        con_bd.executaSQL("select * from tab_funcionarios where cpf_func = '" + cpf + "'");
        
        try {
            if (con_bd.resultset.first())
            {
                JOptionPane.showMessageDialog(null, "Nome: " + con_bd.resultset.getString("nome_func") + "\n" +
                "CPF: " + con_bd.resultset.getString("cpf_func") + "\n" +
                "Endereço: " + con_bd.resultset.getString("ende_func") + "\n" +
                "Número: " + con_bd.resultset.getString("nume_ende_func") + "\n" +
                "Cidade: " + con_bd.resultset.getString("cida_func") + "\n" +
                "Cargo: " + con_bd.resultset.getString("cargo_func") + "\n" +
                "Data Admissão: " + con_bd.resultset.getString("data_admi_func") + "\n" +
                "Data Nascimento: " + con_bd.resultset.getString("data_nasc_func") + "\n" +
                "CEP: " + con_bd.resultset.getString("cep_func") + "\n" +
                "E-mail: " + con_bd.resultset.getString("emai_func") + "\n");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_TblClieMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnReca;
    private javax.swing.JComboBox<String> CboCampo;
    private javax.swing.JLabel LblCampo;
    private javax.swing.JTable TblClie;
    private javax.swing.JTextField TxtCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
