/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Pichau
 */

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Cliente;

public class Desktop extends javax.swing.JFrame {

     
    

    
    public void desabilitar(){
       AreaTrabalho.removeAll();
    }
    /**
     * Creates new form Desktop
     * 
     * 
     */
    public Desktop() {
        initComponents();
        
        //setIcon();
        
      
        this.setExtendedState(MAXIMIZED_BOTH);
        
        
        
        desabilitar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imgs/fundo.jpg"));
        Image image = icon.getImage();
        AreaTrabalho = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        AreaTrabalho.setBorder(javax.swing.BorderFactory.createEmptyBorder(1,1,1,1));
        jMenuBar1 = new javax.swing.JMenuBar();
        Minicio = new javax.swing.JMenu();
        Mvendas = new javax.swing.JMenu();
        Mprodutos = new javax.swing.JMenu();
        Mcadprod = new javax.swing.JMenuItem();
        Mcompras = new javax.swing.JMenu();
        Mclientes = new javax.swing.JMenu();
        Mcliecad = new javax.swing.JMenuItem();
        Mcliecon = new javax.swing.JMenuItem();
        Mfuncionarios = new javax.swing.JMenu();
        Mfunccad = new javax.swing.JMenuItem();
        Mfunccon = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Silveira's Sport");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Silveira Sport"); // NOI18N
        getContentPane().setLayout(null);

        AreaTrabalho.setPreferredSize(new java.awt.Dimension(1600, 900));

        javax.swing.GroupLayout AreaTrabalhoLayout = new javax.swing.GroupLayout(AreaTrabalho);
        AreaTrabalho.setLayout(AreaTrabalhoLayout);
        AreaTrabalhoLayout.setHorizontalGroup(
            AreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
        );
        AreaTrabalhoLayout.setVerticalGroup(
            AreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        getContentPane().add(AreaTrabalho);
        AreaTrabalho.setBounds(0, 0, 1600, 900);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 28));

        Minicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/home.png"))); // NOI18N
        Minicio.setText("Início");
        Minicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinicioActionPerformed(evt);
            }
        });
        jMenuBar1.add(Minicio);

        Mvendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/venda.png"))); // NOI18N
        Mvendas.setText("Vendas");
        jMenuBar1.add(Mvendas);

        Mprodutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/produtos.png"))); // NOI18N
        Mprodutos.setText("Produtos");

        Mcadprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cadastro.png"))); // NOI18N
        Mcadprod.setText("Cadastrar");
        Mcadprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                McadprodActionPerformed(evt);
            }
        });
        Mprodutos.add(Mcadprod);

        jMenuBar1.add(Mprodutos);

        Mcompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/compra.png"))); // NOI18N
        Mcompras.setText("Compras");
        jMenuBar1.add(Mcompras);

        Mclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/clientes.png"))); // NOI18N
        Mclientes.setText("Clientes");

        Mcliecad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cadastro.png"))); // NOI18N
        Mcliecad.setText("Cadastrar");
        Mcliecad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                McliecadActionPerformed(evt);
            }
        });
        Mclientes.add(Mcliecad);

        Mcliecon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/consulta.png"))); // NOI18N
        Mcliecon.setText("Consultar");
        Mcliecon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MclieconActionPerformed(evt);
            }
        });
        Mclientes.add(Mcliecon);

        jMenuBar1.add(Mclientes);

        Mfuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/funcionarios.png"))); // NOI18N
        Mfuncionarios.setText("Funcionários");

        Mfunccad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cadastro.png"))); // NOI18N
        Mfunccad.setText("Cadastrar");
        Mfunccad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MfunccadActionPerformed(evt);
            }
        });
        Mfuncionarios.add(Mfunccad);

        Mfunccon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/consulta.png"))); // NOI18N
        Mfunccon.setText("Consulta");
        Mfunccon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MfuncconActionPerformed(evt);
            }
        });
        Mfuncionarios.add(Mfunccon);

        jMenuBar1.add(Mfuncionarios);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(1616, 939));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MclieconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MclieconActionPerformed
        ConClieFrame concliente = new ConClieFrame();
        AreaTrabalho.add(concliente);
        concliente.setVisible(true);
        concliente.setPosicao();
    }//GEN-LAST:event_MclieconActionPerformed

    private void McliecadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_McliecadActionPerformed
        CadClieFrame cadcliente = new CadClieFrame();
        AreaTrabalho.add(cadcliente);
        cadcliente.setVisible(true);
        cadcliente.setPosicao();
    }//GEN-LAST:event_McliecadActionPerformed

    private void MinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinicioActionPerformed
       desabilitar();
    }//GEN-LAST:event_MinicioActionPerformed

    private void MfunccadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MfunccadActionPerformed
        CadFuncFrame cadfunc = new CadFuncFrame();
        AreaTrabalho.add(cadfunc);
        cadfunc.setVisible(true);
        cadfunc.setPosicao();
    }//GEN-LAST:event_MfunccadActionPerformed

    private void MfuncconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MfuncconActionPerformed
        ConFunFrame confun = new ConFunFrame();
        AreaTrabalho.add(confun);
        confun.setVisible(true);
        confun.setPosicao();
    }//GEN-LAST:event_MfuncconActionPerformed

    private void McadprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_McadprodActionPerformed
        CadProdFrame cadprod = new CadProdFrame();
        AreaTrabalho.add(cadprod);
        cadprod.setVisible(true);
        cadprod.setPosicao();
    }//GEN-LAST:event_McadprodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane AreaTrabalho;
    private javax.swing.JMenuItem Mcadprod;
    private javax.swing.JMenuItem Mcliecad;
    private javax.swing.JMenuItem Mcliecon;
    private javax.swing.JMenu Mclientes;
    private javax.swing.JMenu Mcompras;
    private javax.swing.JMenuItem Mfunccad;
    private javax.swing.JMenuItem Mfunccon;
    private javax.swing.JMenu Mfuncionarios;
    private javax.swing.JMenu Minicio;
    private javax.swing.JMenu Mprodutos;
    private javax.swing.JMenu Mvendas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    /*public Cliente getObjCliente() {
        return objCliente;
    }

    public void setObjCliente(Cliente objCliente) {
        this.objCliente = objCliente;
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imgs/logo.png"))); //To change body of generated methods, choose Tools | Templates.
    }*/

    

}
